### ISSUE TITLE
Rules are unnecessarily ordered

### ISSUE THREAD

**Issue by jnothman** [skope-rules/skope-rules#19]
I think the current code can produce rules that are identical to each other, but in the opposite order. This would reduce the interpretability benefits of the model. Rules should be deduplicated if possible.

**Comment by ngoix** [comment]
Thanks for your comment @jnothman. Do you have experienced duplicated rules using the code? 
I think rules are deduplicated, L360 in skrules/skope_rules.py.
That said, we could return a set of rules instead of a list.

**Comment by jnothman** [comment]
No experience. If you're deduplicating, great.
